### ISSUE TITLE
Kertaus-luennon aihe-ehdotuksiin voi palauttaa tyhjän vastauksen.

### ISSUE THREAD

**Issue by Aikain** [ssuonsyrja/jotu2016#18]
https://moodle2.tut.fi/mod/feedback/complete.php?id=294149&courseid&gopage=0

Kenttään ei ole pakko kirjoittaa mitään, vaan voi sen jättää tyhjäksi ja palauttaa. 

Tämän jälkeen tulee normaalisti ilmoitus siitä, että vastaus palautettu:
![image](https://cloud.githubusercontent.com/assets/5877174/20596790/ca2cbd68-b248-11e6-961f-d68c4fdce186.png)

**Comment by ta-jotu-ass** [comment]
No tuo on tiedossa, eipä se haittaa. Kommentoija voi kirjoittaa uuden kommentin. Tensu.
